data:
  root_folder: "data/raw/SCENTROID_data_06_202025/Metabolic_abnormality_classification/Metabolic_combined"
  columns:
    - Temperature
    - Humidity
    - Hydrogen Sulfide - LC (PPM)
    - Hydrogen (PPM)
    - Nitric Oxide - LC (PPM)
    - VOCs PID - LC (PPM)
    - Air Contaminants (PPM)  
    - Methane - LEL (PPM)
    - Carbon Dioxide - LC (PPM)
  stats_path: "src/data/normalization_stats.json"
  use_stats: false
  min_required_length: 40.0
  min_sequence_length: 40
  max_sequence_length: 1000
  derivative_columns: []
  smoothing_window: null
  iqr_factor: null
  log_columns: []

model:
  hidden_size: 64
  num_layers: 3

train:
  epochs: 160
  batch_size: 8
  learning_rate: 0.0001
  val_ratio: 0.20
  early_stopping_patience: 10
  early_stopping_min_delta: 0.001
  model_save_path: "src/models/checkpoints/lstm_model.pth"
  threshold_path: "src/models/checkpoints/threshold.json"

# Default configuration for scripts
model_type: "lstm"
skip_cv: false
checkpoint: "src/models/checkpoints/lstm_model.pth"
test_folder: "data/test"

