data:
  root_folder: "data/raw"
  columns:
    - Temperature
    - Humidity
    - Hydrogen Sulfide - LC (PPM)
    - Hydrogen (PPM)
    - Nitric Oxide - LC (PPM)
    - Air Contaminants (PPM)
    - VOCs PID - LC (PPM)
    - Methane - LEL (PPM)
    - Carbon Dioxide - LC (PPM)
  stats_path: "src/data/normalization_stats.json"
  use_stats: false
  min_required_length: 50.0
  derivative_columns:
    - Hydrogen Sulfide - LC (PPM)
    - Hydrogen (PPM)
    - Nitric Oxide - LC (PPM)
    - Carbon Dioxide - LC (PPM)

model:
  hidden_size: 128
  num_layers: 3

train:
  epochs: 200
  batch_size: 4
  learning_rate: 0.001
  val_ratio: 0.25
  early_stopping_patience: 10
  model_save_path: "src/models/checkpoints/lstm_model.pth"