_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
data:
    value:
        columns:
            - Temperature
            - Humidity
            - Hydrogen Sulfide - LC (PPM)
            - Hydrogen (PPM)
            - Nitric Oxide - LC (PPM)
            - Air Contaminants (PPM)
            - VOCs PID - LC (PPM)
            - Methane - LEL (PPM)
            - Carbon Dioxide - LC (PPM)
        root_folder: data/raw
        stats_path: src/data/normalization_stats.json
        use_stats: false
model:
    value:
        hidden_size: 128
        num_layers: 3
train:
    value:
        batch_size: 4
        epochs: 200
        learning_rate: 0.001
        model_save_path: src/models/checkpoints/lstm_model.pth
        val_ratio: 0.25
